GSEB_PREFIX = 'http://gseb.org/'
EXAM_CODE = '285soipmahc'
STD_CODE = 'ssc'
FILE_TO_SAVE_SEAT_NAME_PAIR = 'Data/output_10th_2020.txt'
ALPHABET_PREFIXES = ['S', 'P', 'C', 'B', 'A']
SEAT_NUMBER_DIGITS = 7
JUMP_AFTER_FAULUERES_NUMBER = 2
MAX_NUM_CAN_BE_JUMPED = 3